import type { Metadata } from 'next'
import NextAuthProvider from "@/lib/providers";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
return (
        <NextAuthProvider>
            {children}
        </NextAuthProvider>
  )
}
