import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from "@/lib/providers";
import { Nav } from '@/components/nav';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
return (
        <NextAuthProvider>
            {children}
        </NextAuthProvider>
  )
}
